Added PkGs Requirements Check; Updated List of Available VPNs; The Password can now be retrieved from an the PNG File embedded in the VpnBook Website

diff --git a/vpnbook b/vpnbook
--- a/vpnbook
+++ b/vpnbook
@@ -1,8 +1,11 @@
 #!/bin/sh
 
 vpnbook_folder=/home/$(whoami)/.vpnbook
-vpnbook_url=http://www.vpnbook.com/freevpn
+vpnbook_base_url=https://www.vpnbook.com
+vpnbook_url=${vpnbook_base_url}/freevpn
 interactive=1
+timestamp=$(date +%s)
+exit_code=0
 
 # Start functions  
 # Print out the menu
@@ -14,12 +17,12 @@ show_menu(){
     RED_TEXT=`echo "\033[31m"`
     ENTER_LINE=`echo "\033[33m"`
     echo -e "${MENU}*********************************************${NORMAL}"
-    echo -e "${MENU}**${NUMBER} 1)${MENU} Connect to Euro1 ${NORMAL}"
-    echo -e "${MENU}**${NUMBER} 2)${MENU} Connect to Euro2 ${NORMAL}"
+    echo -e "${MENU}**${NUMBER} 1)${MENU} Connect to PL226 ${NORMAL}"
+    echo -e "${MENU}**${NUMBER} 2)${MENU} Connect to DE4 ${NORMAL}"
     echo -e "${MENU}**${NUMBER} 3)${MENU} Connect to US1 ${NORMAL}"
     echo -e "${MENU}**${NUMBER} 4)${MENU} Connect to US2 ${NORMAL}"
-    echo -e "${MENU}**${NUMBER} 5)${MENU} Connect to CA1 ${NORMAL}" 
-    echo -e "${MENU}**${NUMBER} 6)${MENU} Connect to DE1 ${NORMAL}"
+    echo -e "${MENU}**${NUMBER} 5)${MENU} Connect to CA222 ${NORMAL}" 
+    echo -e "${MENU}**${NUMBER} 6)${MENU} Connect to FR1 ${NORMAL}"
     echo -e "${MENU}*********************************************${NORMAL}"
     echo -e "${ENTER_LINE}Press ${RED_TEXT}any other key to exit. ${NORMAL}"
 }
@@ -27,10 +30,9 @@ show_menu(){
 # Print out the help
 usage(){
     echo "usage: vpnbook [[[-s server ] [-i]] | [-h]]"
-	echo "server can be {EURO1, EURO2, UK1, US1, DE1}"
+	echo "server can be {PL226, DE4, US1, US2, CA222, FR1}"
 	echo "if no parameter is set the interactive mode is started."
 }
-
 
 zip_downloader(){
 	base_name=VPNBook.com-OpenVPN
@@ -45,6 +47,21 @@ zip_downloader(){
 		u_country=$(echo $country | tr '[:lower:]' '[:upper:]')		
 		unzip ${vpnbook_folder}/${base_name}-${country}.${ext} -d ${vpnbook_folder}/${u_country}	
 	fi
+}
+
+is_installed(){
+	if ! [ -x "$(command -v $1)" ]; then
+	  echo 'Error: $1 is not installed.' >&2
+	  exit 1
+	fi
+}
+
+check_requirements(){
+	# Check if sudo, curl tesseract and ImageMagick are installed
+	is_installed sudo
+	is_installed curl
+	is_installed tesseract
+	is_installed mogrify
 }
 # End functions 
 
@@ -66,20 +83,30 @@ while [ "$1" != "" ]; do
     shift
 done
 
-echo "Retrieving Password from server"
+# Retrieve the Password URL from the official webpage
+pwd_url=$(curl -s ${vpnbook_url} | grep Password | tr -d ' ' | sed -n '2p' | cut -d \" -f2 | sed 's/bg.*\&//')
+echo "Retrieving Password at the following URL: ${pwd_url}"
 
-# Retrieve the Password from the official webpage
-pwd=$(curl -s ${vpnbook_url} | grep Password | tr -d ' ' | head -n 1 | cut -d '>' -f 3 | cut -d ':' -f 2 | cut -d '<' -f 1)
+# Make sure that the output format is a real PNG file
+curl ${vpnbook_base_url}/${pwd_url} -o /tmp/password-${timestamp}.php
+convertformat /tmp/password-${timestamp}.php /tmp/password-${timestamp}.png
+
+# Make the PNG File a bit neater so that it can be further processed
+mogrify -resize 400% /tmp/password-${timestamp}.png
+
+# Tesseract appends the suffix ".txt" automatically at the end of the output filename 
+tesseract /tmp/password-${timestamp}.png /tmp/password-${timestamp}
+pwd=$(cat /tmp/password-${timestamp}.txt | tr -d '[:space:]')
 
 if [ "${pwd}" == "" ] 
 then
-	echo "Password not retrieved from server"
+	echo "Password not retrieved from server..."
 	echo "Exiting"
-	exit 
+	exit 1
 else
 	mkdir -p ${vpnbook_folder} 	
 	
-	for i in Euro1 Euro2 US1 US2 CA1 DE1
+	for i in PL226 DE4 US1 US2 CA222 FR1
 	do
 		zip_downloader ${i}
 	done
@@ -101,12 +128,12 @@ else
 		read opt
 		
 		case $opt in
-		1) var=EURO1;;
-		2) var=EURO2;;
+		1) var=PL226;;
+		2) var=DE4;;
 		3) var=US1;;
 		4) var=US2;;
-		5) var=CA1;;
-		6) var=DE1;;
+		5) var=CA222;;
+		6) var=FR1;;
 		*) echo "Exit"; exit;;
 		esac
 	else
@@ -116,17 +143,25 @@ else
 	if [ ! $opt -eq 6 ]; then
 		# Make the original variable lowercase
 		l_var=$(echo $var | tr '[:upper:]' '[:lower:]')
-	else
-		l_var=de233
 	fi
 	
 	echo "Starting the Vpn Tunnel"
 	# Login to sudo	
 	sudo -v
 	# Start the connection
-	sudo openvpn --config ${vpnbook_folder}/${var}/vpnbook-${l_var}-tcp443.ovpn --auth-user-pass ${vpnbook_folder}/login.conf > /tmp/vpnbook.log &
-	echo "Vpn Tunnel established"	
+	sudo openvpn --config ${vpnbook_folder}/${var}/vpnbook-${l_var}-tcp443.ovpn --auth-user-pass ${vpnbook_folder}/login.conf > /tmp/vpnbook.log	
+	OPENVPN_EXIT_STATUS=$?
+	
+	if [ ${OPENVPN_EXIT_STATUS} -eq 0  ]; then
+		echo "Vpn Tunnel established"
+	else
+		echo "An Error has occurred while trying to Establish the Vpn Tunnel"
+		exit_code=1
+	fi
+
 	#End Script
-	exit 0
+	echo "Cleaning temporary Files..."
+	rm /tmp/password-${timestamp}.php /tmp/password-${timestamp}.png /tmp/password-${timestamp}.txt
+	exit ${exit_code}
 fi
 
