Fixed Config File Path; Improved Tun Interface Check;

diff --git a/vpnbook b/vpnbook
--- a/vpnbook
+++ b/vpnbook
@@ -29,8 +29,13 @@ usage(){
 
 read_property(){
 	input="$@"
-	temp=`cat $config_file | sed 's/\"//g' | grep -w $input | cut -d ":" -f2`
-	echo ${temp##*|}
+	if [ ! -f ${config_file} ]; then
+		echo "${config_file} does not exist... Aborting..."
+		exit 1
+	else
+		temp=`cat $config_file | sed 's/\"//g' | grep -w $input | cut -d ":" -f2` 
+		echo ${temp##*|}
+	fi
 }
 
 zip_downloader(){
@@ -138,7 +143,7 @@ check_if_up(){
 	
 	local if_id="$@"
 	local if_result=$(ifconfig ${if_id} | grep "${if_id}: flags" | cut -d \: -f1)
-	if [ ${if_result} == "${if_id}"  ]; then
+	if [ "${if_result}" == "${if_id}"  ]; then
 		return 1
 	else
 		return 0
@@ -148,7 +153,8 @@ check_if_up(){
 
 # Variable Declaration
 default_dir=${HOME}/.local/scripts
-vpnbook_folder=$HOME/.vpnbook
+config_file=${default_dir}/vpnbook.config
+vpnbook_folder=${HOME}/.vpnbook
 vpnbook_base_url=https://www.vpnbook.com
 vpnbook_url=${vpnbook_base_url}/freevpn
 tesseract_service_url=https://api.ocr.space/parse/image
diff --git a/vpnbook_wrapper b/vpnbook_wrapper
--- a/vpnbook_wrapper
+++ b/vpnbook_wrapper
@@ -3,8 +3,13 @@
 # Begin Functions
 read_property(){
 	input="$@"
-	temp=`cat $config_file | sed 's/\"//g' | grep -w $input | cut -d ":" -f2`
-	echo ${temp##*|}
+	if [ ! -f ${config_file} ]; then
+		echo "${config_file} does not exist... Aborting..."
+		exit 1
+	else
+		temp=`cat $config_file | sed 's/\"//g' | grep -w $input | cut -d ":" -f2` 
+		echo ${temp##*|}
+	fi
 }
 
 open_xterm_terminal(){
@@ -40,7 +45,7 @@ wait_for_seconds(){
 }
 
 check_if_up(){
-	wait_for_seconds 10
+	wait_for_seconds 5
 	
 	local if_id="$@"
 	local if_result=$(ifconfig ${if_id} | grep "${if_id}: flags" | cut -d \: -f1)
